import Header from '@/components/Header'
import './styles.scss'
import Footer from '@/components/Footer'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const Year =  new Date().getFullYear()
  return (
    <html lang="en">
      <body>
        <Header />
        <main id="main-content">
          <div className="container">
            {children}
          </div>
        </main>
        <Footer />
      </body>
    </html>
  )
}
