

export const site = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    keywords: 'nextjs, react, reactjs, create next app',
    author: 'Vercel',
    }

export const navLinks = [
    {
        name: 'Home',
        url: '/'
    },
    {
        name: 'About',
        url: '/about'
    },
    {
        name: 'Contact',
        url: '/contact'
    }
]
